version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    environment:       
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: 1235 
      POSTGRES_DB: db_show 
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST: db:3306
      - WORDPRESS_DB_USER: wordpress
      - WORDPRESS_DB_PASSWORD: wordpress
volumes:
  db_data: 
